Adding tests
bitcoinvault/3key-generator pull request #19
Opened 2020-12-23 10:13 UTC by oskarbogucki

- Tests verify whether the page is displayed correctly
 - verifying changing app languages correctly
 - verifying generating of new keys (private and public qr, phrases and multiline)
 - checking if page response status is right
 - tests accross different devices and multiple environments (local, cloudbest, bitcoinvault)

2020-12-23 10:20 UTC, marek-siemieniuk-morawski approved these changes

2020-12-23 10:41 UTC, aleparty commented on tests/e2e/support/pages/keyGenerator.js
> +    '.language-picker .MuiSelect-root.MuiSelect-select.MuiSelect-selectMenu.MuiInputBase-input.MuiInput-input',
this could be simplified to '.MuiInput-input' or '.language-picker'

2020-12-28 12:43 UTC, KedziaPawel commented
this PR should be to develop not to master

would be nice to use typescript in cypress

2020-12-30 16:58 UTC, marek-siemieniuk-morawski requested changes
Please change the selectors there because it's a problem.

Also, as @KedziaPawel mentioned, please change the base branch.

2020-12-30 16:58 UTC, marek-siemieniuk-morawski commented on tests/e2e/support/pages/keyGenerator.js
> +  title: 'h2',
it's very risky to use as a selector an html element. Use CSS class instead of something else but more specific than this one.

2020-12-30 16:58 UTC, marek-siemieniuk-morawski commented on tests/e2e/support/pages/keyGenerator.js
> +};
empty line between `};` and ` export default`?

2020-12-30 16:59 UTC, marek-siemieniuk-morawski commented
> would be nice to use typescript in cypress

Agree, but let's do that in the next PR

2021-01-11 12:22 UTC, closed without merging